[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all admin routes to handle client-side routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirect all app detail pages to handle dynamic routing
[[redirects]]
  from = "/:slug"
  to = "/:slug/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

  [build.processing.html]
  pretty_urls = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://static.cloudflareinsights.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.google-analytics.com https://stats.g.doubleclick.net;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Priority = "high"

# Cache critical CSS separately with longer TTL
[[headers]]
  for = "/_astro/critical-*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Priority = "high"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache images with long TTL
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Priority = "low"

# Cache fonts with long TTL
[[headers]]
  for = "/*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

# Environment variables (these will be set in Netlify dashboard)
# VITE_SUPABASE_URL = "your_supabase_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"