[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all admin routes to handle client-side routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirect all app detail pages to handle dynamic routing
[[redirects]]
  from = "/:slug"
  to = "/:slug/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!US"]}

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

  [build.processing.html]
  pretty_urls = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co; prefetch-src 'self';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
# VITE_SUPABASE_URL = "your_supabase_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"