[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Serve static assets with correct MIME types FIRST (before redirects)
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# Redirect all admin routes to handle client-side routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirect all app detail pages to handle dynamic routing
[[redirects]]
  from = "/:slug"
  to = "/:slug/index.html"
  status = 200

# Handle 404s (must be last)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

  [build.processing.html]
  pretty_urls = false

  [build.processing.images]
  compress = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://static.cloudflareinsights.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.google-analytics.com https://stats.g.doubleclick.net;"

# CRITICAL: CSS files must be served with correct MIME type
[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Priority = "high"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Priority = "high"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Priority = "high"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 
    X-Content-Type-Options = "nosniff"

# Cache images with long TTL
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Priority = "low"

# Cache fonts with long TTL
[[headers]]
  for = "/*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"

# Image optimization headers
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,avif}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Content-Disposition = "inline"
    X-Content-Type-Options = "nosniff"
    Accept-CH = "DPR, Width, Viewport-Width"
    Content-DPR = "1.0"
    Timing-Allow-Origin = "*"
    Priority = "auto"

# Add specific cache headers for CDN images
[[headers]]
  for = "/cdn.dexapk.com/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Timing-Allow-Origin = "*"

# Environment variables (these will be set in Netlify dashboard)
# VITE_SUPABASE_URL = "your_supabase_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"