[build]
  publish = "dist"
  command = "npm run build"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://static.cloudflareinsights.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.google-analytics.com https://stats.g.doubleclick.net;"

# CSS files with correct MIME types
[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    X-Content-Type-Options = "nosniff"

# JavaScript files with correct MIME types
[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    X-Content-Type-Options = "nosniff"

# Legacy assets support
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images with long TTL
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Priority = "low"

# Cache fonts with long TTL
[[headers]]
  for = "/*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"

# Environment variables (these will be set in Netlify dashboard)
# VITE_SUPABASE_URL = "your_supabase_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"